<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Hash;

class UserStoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\Rule|array|string>
     */

    public function getValidatorInstance()
    {


        parent::getValidatorInstance();        // TODO: Change the autogenerated stub

        $this->HashPassword();

        return $this;

    }

    public function rules(): array
    {
        return [
            'first_name' => 'required',
            'second_name' => 'required',
            'last_name' => 'required',
            'email' => 'required|unique:users',
            'phone' => 'required|unique:users',
            'birthday' => 'required',
            'sex' => 'required|between:0,1',
            'password' => 'required|confirmed',
        ];
    }

    protected function HashPassword()
    {

        $this->merge([
            'password' => Hash::make($this->request->get('password')),
            'password_confirmation' => Hash::make($this->request->get('password_confirmation'))
        ]);
    }

    public function messages()
    {
        return [
            'first_name.required' => 'Имя обязательное поле'
        ]; // TODO: Change the autogenerated stub
    }
}
